import React from 'react';
import { 
  ArrowBack,
  School,
  RecordVoiceOver,
  Headphones,
  MenuBook,
  Edit,
  CheckCircle,
  Cancel,
  Home,
  Person,
  Settings,
  Logout,
  PlayArrow,
  Pause,
  Stop,
  VolumeUp,
  VolumeOff,
  SkipNext,
  SkipPrevious,
  Replay,
  Forward10,
  Replay10,
  ExpandMore,
  ExpandLess,
  KeyboardArrowDown,
  KeyboardArrowUp,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  Close,
  Menu,
  MoreVert,
  Info,
  Warning,
  ErrorOutline,
  Star,
  StarBorder,
  Favorite,
  FavoriteBorder,
  Share,
  Download,
  Upload,
  Search,
  FilterList,
  Sort,
  ViewList,
  ViewModule,
  GridView,
  Refresh,
  Sync,
  Wifi,
  WifiOff,
  Notifications,
  NotificationsOff,
  SportsEsports,
  ArrowForward,
  Bolt,
  Language,
  WorkspacePremium,
  EditNote,
  Quiz,
  Work,
  Mic,
  Assignment,
  Send,
  Lightbulb,
  Schedule,
  TrendingUp,
  Celebration,
  ThumbUp,
  Build,
  Psychology,
  Assessment,
  AssignmentTurnedIn,
  AutoAwesome,
  StickyNote2,
  Article,
  Rule,
  Email,
  AutoStories,
  Checklist,
  Category,
  Check,
  VideogameAsset,
  Style
} from '@mui/icons-material';

// Map of Material Icon names to Material-UI components
const iconMap = {
  'arrow_back': ArrowBack,
  'school': School,
  'record_voice_over': RecordVoiceOver,
  'headphones': Headphones,
  'menu_book': MenuBook,
  'edit': Edit,
  'check_circle': CheckCircle,
  'cancel': Cancel,
  'home': Home,
  'person': Person,
  'settings': Settings,
  'logout': Logout,
  'play_arrow': PlayArrow,
  'pause': Pause,
  'stop': Stop,
  'volume_up': VolumeUp,
  'volume_off': VolumeOff,
  'skip_next': SkipNext,
  'skip_previous': SkipPrevious,
  'replay': Replay,
  'forward_10': Forward10,
  'replay_10': Replay10,
  'expand_more': ExpandMore,
  'expand_less': ExpandLess,
  'keyboard_arrow_down': KeyboardArrowDown,
  'keyboard_arrow_up': KeyboardArrowUp,
  'keyboard_arrow_left': KeyboardArrowLeft,
  'keyboard_arrow_right': KeyboardArrowRight,
  'close': Close,
  'menu': Menu,
  'more_vert': MoreVert,
  'info': Info,
  'warning': Warning,
  'error': ErrorOutline,
  'error_outline': ErrorOutline,
  'success': CheckCircle,
  'star': Star,
  'star_border': StarBorder,
  'favorite': Favorite,
  'favorite_border': FavoriteBorder,
  'share': Share,
  'download': Download,
  'upload': Upload,
  'search': Search,
  'filter_list': FilterList,
  'sort': Sort,
  'view_list': ViewList,
  'view_module': ViewModule,
  'grid_view': GridView,
  'refresh': Refresh,
  'sync': Sync,
  'wifi': Wifi,
  'wifi_off': WifiOff,
  'notifications': Notifications,
  'notifications_off': NotificationsOff,
  'sports_esports': SportsEsports,
  'arrow_forward': ArrowForward,
  'bolt': Bolt,
  'language': Language,
  'workspace_premium': WorkspacePremium,
  'edit_note': EditNote,
  'quiz': Quiz,
  'work': Work,
  'mic': Mic,
  'assignment': Assignment,
  'send': Send,
  'lightbulb': Lightbulb,
  'schedule': Schedule,
  'trending_up': TrendingUp,
  'celebration': Celebration,
  'thumb_up': ThumbUp,
  'build': Build,
  'psychology': Psychology,
  'assessment': Assessment,
  'assignment_turned_in': AssignmentTurnedIn,
  'auto_awesome': AutoAwesome,
  'sticky_note_2': StickyNote2,
  'article': Article,
  'rule': Rule,
  'email': Email,
  'auto_stories': AutoStories,
  'checklist': Checklist,
  'category': Category,
  'check': Check,
  'videogame_asset': VideogameAsset,
  'style': Style
};

/**
 * MaterialIcon component that renders Material-UI icons instead of font icons
 * @param {string} name - The Material Icon name (e.g., 'arrow_back', 'school')
 * @param {string} className - Additional CSS classes
 * @param {object} style - Inline styles
 * @param {string} fontSize - Icon size: 'small', 'medium', 'large', or custom
 */
const MaterialIcon = ({ 
  name, 
  className = '', 
  style = {}, 
  fontSize = 'medium',
  ...props 
}) => {
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    console.warn(`MaterialIcon: Icon "${name}" not found. Available icons:`, Object.keys(iconMap));
    return <span className={className} style={style} {...props}>{name}</span>;
  }
  
  return (
    <IconComponent 
      className={className}
      style={style}
      fontSize={fontSize}
      {...props}
    />
  );
};

export default MaterialIcon; 